volumes:
  postgres_data:

networks:
  swarm-network:
    driver: overlay

services:
  postgres:
    image: postgres
    networks:
      - swarm-network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      replicas: 2

  backend:
    image: localhost:5000/resource-manager-backend
    networks:
      - swarm-network
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      LOGOUT_URL: ${LOGOUT_URL}
      PORT: ${BACKEND_PORT}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      FRONTEND_URL: ${FRONTEND_URL}
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_BACKEND_REALM}
      KEYCLOAK_CLIENT: ${KEYCLOAK_BACKEND_CLIENT}
      KEYCLOAK_SECRET: ${KEYCLOAK_BACKEND_SECRET}
      KEYCLOAK_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    depends_on:
      - postgres
    deploy:
      replicas: 2

  frontend:
    image: localhost:5000/resource-manager-frontend
    networks:
      - swarm-network
    ports:
      - "443:443"
    environment:
      VITE_ROOT_URL: ${FRONTEND_URL}
      VITE_BACKEND_URL: ${BACKEND_URL}
      VITE_KEYCLOAK_URL: ${KEYCLOAK_URL}
      VITE_KEYCLOAK_REALM: ${KEYCLOAK_FRONTEND_REALM}
      VITE_KEYCLOAK_CLIENT: ${KEYCLOAK_FRONTEND_CLIENT}
    depends_on:
      - backend
    deploy:
      replicas: 2