apiVersion: v1
kind: Secret
metadata:
  name: backend-env
  namespace: resource-manager
type: Opaque
stringData:
  PORT: "${BACKEND_PORT}"
  LOGOUT_URL: ${BACKEND_LOGOUT_URL}
  DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql.postgresql.svc.cluster.local/${POSTGRES_DB}
  FRONTEND_URL: ${FRONTEND_URL}
  KEYCLOAK_URL: ${KEYCLOAK_URL}
  KEYCLOAK_REALM: ${KEYCLOAK_BACKEND_REALM}
  KEYCLOAK_CLIENT: ${KEYCLOAK_BACKEND_CLIENT}
  KEYCLOAK_SECRET: ${KEYCLOAK_BACKEND_SECRET}
  KEYCLOAK_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USERNAME}
  KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}