apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ${CLUSTER_ISSUER}
spec:
  acme:
    email: ${CERT_EMAIL}
    server: ${CERT_SERVER}
    privateKeySecretRef:
      name: dns-private-key
      key: tls.key
    solvers:
      - dns01:
          cloudflare:
            email: ${CERT_EMAIL}
            apiTokenSecretRef:
              name: ${CERT_TOKEN}
              key: api-token